[application]
name="rss-frontend"
default_platform = "web"

[web.resource]
style = [
    "https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100..900;1,100..900&family=Patua+One&display=swap",
    "./assets/style.css"
]
[web.resource.dev]

[web.app]
title="SimpRSS"

[web.watcher]
index_on_404 = true