services:
  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - type: bind
        source: database/dbscript.sql
        target: /docker-entrypoint-initdb.d/dbscript.sql
  api:
    build: rss-api/.
    ports:
      - ${backend_port}:3000
    environment:
      - IS_DOCKER_COMPOSED=${deploy_origin}
      - RSS_API_DB=mysql://root:test@172.18.0.2:3306/rss
    restart: always
  frontend:
    build:
      context: vue-frontend/
      dockerfile: Dockerfile
      args:
        - backend_url=${backend_url}
    ports:
      - ${frontend_port}:80